/**
 * Cloudflare Environment Types
 * Generated by: pnpm run cf-typegen
 *
 * This file contains TypeScript types for Cloudflare Workers bindings.
 * Run `pnpm run cf-typegen` in apps/nextjs to regenerate from wrangler.toml.
 *
 * @see https://opennext.js.org/cloudflare/get-started
 */

interface CloudflareEnv {
  // Service bindings
  WORKER_SELF_REFERENCE: Fetcher;
  
  // Asset bindings
  ASSETS: Fetcher;
  
  // Environment variables from wrangler.toml [vars]
  NODE_VERSION: string;
  
  // Add KV namespaces here when configured
  // Example: MY_KV: KVNamespace;
  
  // Add R2 buckets here when configured
  // Example: NEXT_INC_CACHE_R2_BUCKET: R2Bucket;
  
  // Add D1 databases here when configured
  // Example: MY_DB: D1Database;
}

// Make CloudflareEnv available globally in Workers
declare global {
  interface CloudflareContext {
    env: CloudflareEnv;
    ctx: ExecutionContext;
  }
}

// Export for module usage
export type { CloudflareEnv };
