packages:
  - apps/*
  - packages/*
  - tooling/*

ignoredBuiltDependencies:
  - '@clerk/shared'
  - '@prisma/engines'
  - '@tsparticles/engine'
  - '@vercel/speed-insights'
  - bufferutil
  - contentlayer2
  - core-js
  - core-js-pure
  - esbuild
  - prisma
  - protobufjs
  - puppeteer
  - sharp
  - utf-8-validate

overrides:
  cross-spawn@>=7.0.0 <7.0.5: '>=7.0.5'
  js-yaml@>=4.0.0 <4.1.1: '>=4.1.1'
  lodash@>=4.0.0 <=4.17.22: '>=4.17.23'
  next@>=10.0.0 <15.5.10: '>=15.5.10'
  next@>=13.0.0 <15.0.8: '>=15.0.8'
  prismjs@<1.30.0: '>=1.30.0'
  tmp@<=0.2.3: '>=0.2.4'
  ws@>=8.0.0 <8.17.1: '>=8.17.1'
