-- Add Database Comments for Schema Documentation
-- Migration: 20260221_add_database_comments

-- Purpose: Add descriptive comments to tables and columns for better documentation
-- Impact: Improves database documentation visible in admin tools (pgAdmin, DBeaver, etc.)
-- Note: Comments have zero performance impact - they are metadata only

-- ============================================================================
-- TABLE COMMENTS
-- ============================================================================

-- User table: Core user data from Clerk authentication
COMMENT ON TABLE "User" IS 'Core user data synchronized from Clerk authentication. Contains profile information and serves as the primary entity for user management.';

-- Customer table: Subscription and billing information
COMMENT ON TABLE "Customer" IS 'Customer billing and subscription data. Links users to Stripe for payment processing. Each user has at most one customer record.';

-- Account table: OAuth provider connections
COMMENT ON TABLE "Account" IS 'OAuth provider connections for users. Stores tokens and provider-specific data for authentication providers (Google, GitHub, etc.).';

-- Session table: Active user sessions
COMMENT ON TABLE "Session" IS 'Active user sessions for authentication. Used by NextAuth/Clerk for session management.';

-- VerificationToken table: Email verification tokens
COMMENT ON TABLE "VerificationToken" IS 'Email verification tokens for account confirmation and password reset flows.';

-- K8sClusterConfig table: Kubernetes cluster configurations
COMMENT ON TABLE "K8sClusterConfig" IS 'Kubernetes cluster configurations managed by users. Supports soft delete for audit trail preservation. Each cluster belongs to one user.';

-- StripeWebhookEvent table: Stripe webhook event processing
COMMENT ON TABLE "StripeWebhookEvent" IS 'Stripe webhook events for idempotent processing. Tracks all incoming webhooks and their processing status for subscription sync.';

-- ============================================================================
-- USER TABLE COLUMN COMMENTS
-- ============================================================================

COMMENT ON COLUMN "User"."id" IS 'Unique user identifier (UUID). Generated by Clerk and used as primary key across all tables.';
COMMENT ON COLUMN "User"."name" IS 'User display name. Optional, may be null for users who haven not set a name.';
COMMENT ON COLUMN "User"."email" IS 'User email address. Unique constraint, used for notifications and Stripe checkout.';
COMMENT ON COLUMN "User"."emailVerified" IS 'Timestamp when email was verified. Null if not yet verified.';
COMMENT ON COLUMN "User"."image" IS 'URL to user avatar image. Optional, may be provided by OAuth provider.';

-- ============================================================================
-- CUSTOMER TABLE COLUMN COMMENTS
-- ============================================================================

COMMENT ON COLUMN "Customer"."id" IS 'Auto-incrementing primary key for customer record.';
COMMENT ON COLUMN "Customer"."authUserId" IS 'Foreign key to User table. Unique constraint ensures one customer per user.';
COMMENT ON COLUMN "Customer"."name" IS 'Customer display name, may differ from user name.';
COMMENT ON COLUMN "Customer"."plan" IS 'Current subscription plan: FREE, PRO, or BUSINESS. Null for users without a plan.';
COMMENT ON COLUMN "Customer"."stripeCustomerId" IS 'Stripe customer ID (format: cus_*). Unique, null until first Stripe interaction.';
COMMENT ON COLUMN "Customer"."stripeSubscriptionId" IS 'Stripe subscription ID (format: sub_*). Unique, null for users without active subscription.';
COMMENT ON COLUMN "Customer"."stripePriceId" IS 'Stripe price ID for current subscription. Used to determine plan tier and interval.';
COMMENT ON COLUMN "Customer"."stripeCurrentPeriodEnd" IS 'End of current billing period. Used to determine if subscription is active.';
COMMENT ON COLUMN "Customer"."createdAt" IS 'Timestamp when customer record was created.';
COMMENT ON COLUMN "Customer"."updatedAt" IS 'Timestamp when customer record was last updated. Automatically maintained by trigger.';

-- ============================================================================
-- ACCOUNT TABLE COLUMN COMMENTS
-- ============================================================================

COMMENT ON COLUMN "Account"."id" IS 'Unique account identifier (UUID).';
COMMENT ON COLUMN "Account"."userId" IS 'Foreign key to User table. Cascades on delete.';
COMMENT ON COLUMN "Account"."type" IS 'OAuth provider type (oauth, email, credentials, etc.).';
COMMENT ON COLUMN "Account"."provider" IS 'OAuth provider name (google, github, etc.).';
COMMENT ON COLUMN "Account"."providerAccountId" IS 'Account ID from the OAuth provider.';
COMMENT ON COLUMN "Account"."refresh_token" IS 'OAuth refresh token for token renewal.';
COMMENT ON COLUMN "Account"."access_token" IS 'OAuth access token for API calls.';
COMMENT ON COLUMN "Account"."expires_at" IS 'Unix timestamp when access token expires.';
COMMENT ON COLUMN "Account"."token_type" IS 'OAuth token type (usually Bearer).';
COMMENT ON COLUMN "Account"."scope" IS 'OAuth scopes granted by the user.';
COMMENT ON COLUMN "Account"."id_token" IS 'OpenID Connect ID token.';
COMMENT ON COLUMN "Account"."session_state" IS 'OAuth session state for CSRF protection.';

-- ============================================================================
-- SESSION TABLE COLUMN COMMENTS
-- ============================================================================

COMMENT ON COLUMN "Session"."id" IS 'Unique session identifier (UUID).';
COMMENT ON COLUMN "Session"."sessionToken" IS 'Session token for cookie-based authentication. Unique constraint.';
COMMENT ON COLUMN "Session"."userId" IS 'Foreign key to User table. Cascades on delete.';
COMMENT ON COLUMN "Session"."expires" IS 'Timestamp when session expires. Used for session cleanup.';

-- ============================================================================
-- VERIFICATIONTOKEN TABLE COLUMN COMMENTS
-- ============================================================================

COMMENT ON COLUMN "VerificationToken"."identifier" IS 'Email address or identifier for the verification.';
COMMENT ON COLUMN "VerificationToken"."token" IS 'Unique verification token. Unique constraint.';
COMMENT ON COLUMN "VerificationToken"."expires" IS 'Timestamp when token expires. Used for token cleanup.';

-- ============================================================================
-- K8SCLUSTERCONFIG TABLE COLUMN COMMENTS
-- ============================================================================

COMMENT ON COLUMN "K8sClusterConfig"."id" IS 'Auto-incrementing primary key for cluster configuration.';
COMMENT ON COLUMN "K8sClusterConfig"."name" IS 'Cluster name. Must be 1-100 characters, alphanumeric with hyphens. Check constraint enforces format.';
COMMENT ON COLUMN "K8sClusterConfig"."location" IS 'Cluster geographic location/region. Must be 1-50 characters. Check constraint enforces format.';
COMMENT ON COLUMN "K8sClusterConfig"."authUserId" IS 'Foreign key to User table. Restricts delete to prevent orphaned clusters.';
COMMENT ON COLUMN "K8sClusterConfig"."plan" IS 'Subscription plan for this cluster. Defaults to FREE.';
COMMENT ON COLUMN "K8sClusterConfig"."network" IS 'Network configuration for the cluster. Optional.';
COMMENT ON COLUMN "K8sClusterConfig"."createdAt" IS 'Timestamp when cluster was created. Indexed for time-based queries.';
COMMENT ON COLUMN "K8sClusterConfig"."updatedAt" IS 'Timestamp when cluster was last updated. Automatically maintained by trigger.';
COMMENT ON COLUMN "K8sClusterConfig"."status" IS 'Cluster status: PENDING, CREATING, INITING, RUNNING, STOPPED, or DELETED.';
COMMENT ON COLUMN "K8sClusterConfig"."deletedAt" IS 'Soft delete timestamp. Null for active clusters, set when soft deleted. Indexed for filtering.';

-- ============================================================================
-- STRIPEWEBHOOKEVENT TABLE COLUMN COMMENTS
-- ============================================================================

COMMENT ON COLUMN "StripeWebhookEvent"."id" IS 'Stripe event ID. Unique, used for idempotent processing.';
COMMENT ON COLUMN "StripeWebhookEvent"."eventType" IS 'Stripe event type (e.g., customer.subscription.updated). Indexed for filtering.';
COMMENT ON COLUMN "StripeWebhookEvent"."processed" IS 'Whether the webhook has been processed. Indexed for cleanup queries.';
COMMENT ON COLUMN "StripeWebhookEvent"."createdAt" IS 'Timestamp when webhook was received. Indexed for time-based queries.';
COMMENT ON COLUMN "StripeWebhookEvent"."updatedAt" IS 'Timestamp when webhook record was last updated. Automatically maintained by trigger.';

-- ============================================================================
-- NOTES
-- ============================================================================
-- 
-- Benefits of database comments:
-- 1. Documentation is visible in database admin tools (pgAdmin, DBeaver, psql)
-- 2. Helps with onboarding new developers
-- 3. Self-documenting schema for DBAs and support teams
-- 4. Zero performance impact - comments are metadata only
-- 5. Can be queried via PostgreSQL system catalogs:
--    SELECT obj_description('public."User"'::regclass);
--    SELECT col_description('public."User"'::regclass, 1);
--
-- Rollback Strategy:
-- COMMENT ON TABLE "TableName" IS NULL;
-- COMMENT ON COLUMN "TableName"."columnName" IS NULL;
